services:
  _defaults:
    public: true

  GinCms\Bundle\MobileAppSettingsBundle\Graphql\Type\MobileSettingsType:
    class: GinCms\Bundle\MobileAppSettingsBundle\Graphql\Type\MobileSettingsType
    tags:
      - { name: 'graphqlite.type' }
